### ISSUE TITLE
Saving max level

### ISSUE THREAD

**Issue by Majkl47** [Majkl47/cm-dev-1.0#1]
**TODO:**
- [x] Implement maxLevel attribute
- [x] Implement methods loadMaxLevel, saveMaxLevel in class _Saves_
- [x] Add saving maxLevel in game implementation
- [ ] Test maxLevel behaviour
