### ISSUE TITLE
Switching levels

### ISSUE THREAD

**Issue by Majkl47** [Majkl47/cm-dev-1.0#10]
**TODO:**
- [x] Implement switching mechanism in class _GameScreen_: When player reaches the finish, game will switch current level items
- [x] Try adding a new level
- [ ] Test switching mechanism
