### ISSUE TITLE
Implementation of start point

### ISSUE THREAD

**Issue by Majkl47** [Majkl47/cm-dev-1.0#14]
**TODO:**
- [x] Refactor start point position:
  - [x] Add to every level its own start position
  - [x] Implement changes to _GameScreen_ class
- [ ] Test new start position
