### ISSUE TITLE
Create ending screen

### ISSUE THREAD

**Issue by Majkl47** [Majkl47/cm-dev-1.0#5]
**TODO:**
- [x] Create new class _EndingScreen_ in package screens
- [x] Implement functionality: When last level is solved, game will redirect to the ending screen
- [x] There will be confirm button to redirect to the _MainMenu_ class
- [ ] Test correct switching to ending screen
