### ISSUE TITLE
BACK key functionality

### ISSUE THREAD

**Issue by Majkl47** [Majkl47/cm-dev-1.0#6]
**TODO:**
- [x] Catch BACK key press
- [x] Implement behaviour of BACK key on:
  - [x] _GameScreen_
  - [x] _PauseMenu_
  - [x] _LevelScreen_
  - [x] _MainMenu_
- [ ] Test behaviour of BACK key
