### ISSUE TITLE
Saving and loading gamestate

### ISSUE THREAD

**Issue by Majkl47** [Majkl47/cm-dev-1.0#7]
**TODO:**
- [x] Implement loading gamestate when inintializing game
- [x] Implement saving gamestate when leaving _GameScreen_
- [ ] Test loading when file with saves exists
- [ ] Test loading when file with saves doesnt exist
- [ ] Test correct saving
